# add -Wall to try to catch everything we can.
ccflags-y += -Wall

ifeq ($(CONFIG_VIBRATOR_NOISE_CAMERA),y)
	ccflags-y += -DCONFIG_VIBRATOR_NOISE_CAMERA
endif

ldo_vibrator_mmi-y += moto_ldo_vibrator.o

obj-y += ldo_vibrator_mmi.o
